/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.travel;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Cursor;

/**
 *
 * @author kec
 */
public class MainMenuScreen1 extends javax.swing.JFrame {

	/**
	 * Creates new form MainMenuScreen1
	 */
	public MainMenuScreen1() {
		initComponents();
		Color backgroundcolor = new Color(100, 235, 186);
		this.getContentPane().setBackground(backgroundcolor);
		setVisible(true);
		setResizable(false);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		jLabel2 = new javax.swing.JLabel();
		jLabel2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			@Override
			public void windowClosing(java.awt.event.WindowEvent evt) {
				formWindowClosing(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel1.setText("CLICK HERE FOR FLIGHT BOOKING");
		jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jLabel1MouseClicked(evt);
			}
		});

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
		jLabel2.setText("CLICK HERE FOR HOTEL BOOKING");
		jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
			@Override
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				try {
					jLabel2MouseClicked(evt);
				} catch (ClassNotFoundException ex) {
					// TODO Auto-generated catch block
					Logger.getLogger(flightBooking.class.getName()).log(Level.SEVERE, null, ex);
				} catch (SQLException ex) {
					// TODO Auto-generated catch block
					Logger.getLogger(flightBooking.class.getName()).log(Level.SEVERE, null, ex);
				}
			}
		});

		//jLabel5.setIcon(new javax.swing.ImageIcon("plane.jpeg")); // NOI18N

		//jLabel6.setIcon(new javax.swing.ImageIcon("hotel.jpeg")); // NOI18N
		jLabel6.setText("jLabel6");

		lblNewLabel = new JLabel("New label");
		lblNewLabel.setIcon(new ImageIcon("flight.jpg"));

		lblNewLabel_1 = new JLabel("New label");
		lblNewLabel_1.setIcon(new ImageIcon("hotel.jpg"));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel3)
						.addPreferredGap(ComponentPlacement.RELATED, 1011, Short.MAX_VALUE).addComponent(jLabel4)
						.addGap(48))
				.addGroup(layout.createSequentialGroup().addGap(77)
						.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 267, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED, 301, Short.MAX_VALUE).addComponent(jLabel2)
						.addGap(183))
				.addGroup(layout.createSequentialGroup().addGap(19).addComponent(jLabel5).addGap(36)
						.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 355, GroupLayout.PREFERRED_SIZE)
						.addContainerGap(659, Short.MAX_VALUE))
				.addGroup(layout.createSequentialGroup().addGap(81)
						.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 394, GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
						.addComponent(lblNewLabel_1, GroupLayout.PREFERRED_SIZE, 377, GroupLayout.PREFERRED_SIZE)
						.addGap(67)));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.TRAILING).addGroup(layout.createSequentialGroup()
				.addContainerGap(223, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(lblNewLabel, GroupLayout.PREFERRED_SIZE, 317, GroupLayout.PREFERRED_SIZE)
						.addComponent(lblNewLabel_1, GroupLayout.PREFERRED_SIZE, 295, GroupLayout.PREFERRED_SIZE))
				.addGap(27)
				.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
						.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
						.addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGap(16)
				.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
						.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGap(30)
				.addGroup(layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel1).addComponent(jLabel2))
				.addGap(96)));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel1MouseClicked
		try {
			// TODO add your handling code here:
			flightBooking f = new flightBooking();
		} catch (SQLException ex) {
			Logger.getLogger(MainMenuScreen1.class.getName()).log(Level.SEVERE, null, ex);
		} catch (ClassNotFoundException ex) {
			Logger.getLogger(MainMenuScreen1.class.getName()).log(Level.SEVERE, null, ex);
		}
	}// GEN-LAST:event_jLabel1MouseClicked

	private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) throws ClassNotFoundException, SQLException {// GEN-FIRST:event_jLabel2MouseClicked
		hotelBooking hb = new hotelBooking();
	}// GEN-LAST:event_jLabel2MouseClicked

	private void formWindowClosing(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosing
		// TODO add your handling code here:
	}// GEN-LAST:event_formWindowClosing

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainMenuScreen1.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainMenuScreen1.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainMenuScreen1.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainMenuScreen1.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new MainMenuScreen1().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private JLabel lblNewLabel;
	private JLabel lblNewLabel_1;
}
